let CardList = [
    "放眼世界、 征服宇宙 <br><br> You are the king of the galaxy.",
        "現在這樣就很好了！<br><br>Have a nice day.",
        "這個很雷<br><br>Thor say Yes!",
        "魔鬼藏在細節裡<br><br>The devil is in the details.",
        "開心<br><br>｡:.ﾟヽ( * ´∀`)ﾉﾟ.:｡ ",
        "りしれ供さ小<br><br>WTF",
        "沒有什麼事是炸雞不能解決的<br><br>Max knows everything",
        "先做再說<br><br>Just Do It",
        "換個角度思考<br><br>Try a different angle",
        "保持彈性<br><br>Imagine yourself as water (or cat)",
        "休息了<br><br>Hibernate Mode",
        "在有跟沒有之間<br><br>Yes ...and No",
        "把腦袋天線打開<br><br>Open your sensor",
        "你應該先問對問題<br><br>Ask the right question fisrt",
        "嗯嗯<br><br>Mm-hmmm",
        "勿忘世上苦人多<br><br>You ungrateful bastard!",
        "聽聽就好<br><br>Go in one ear and out the other",
        "不錯，但是...<br><br>Nice, but...",
        "放下你的偶包和自我<br><br>You are not as important as you think you are.",
        "深呼吸<br><br>Breath",
        "可憐啊！<br><br>Oh, Poor you!",
        "你確定？<br><br>Are you sure?",
        "愛與包容<br><br>Peace & Love",
        "不宜上班<br><br>Work From Home",
        "便利貼大法好<br><br>Post-it! (3M only!)",
        "拿起點點貼紙投票吧<br><br>Dot voting time",
        "老闆說了算<br><br>Boss say so",
        "正面對決！<br><br>Who Pa Who",
        "換個方式溝通看看<br><br>Try speaking in layman's terms.",
        "當個有想法的人<br><br>Use your brain",
        "慢慢來，比較快<br><br>Slow is the new fashion",
        "舊的不去新的不來<br><br>Happy New Year",
        "去問PM<br><br>Ask your PM (If you have one.)",
        "改完一次那你有想過再改第二次嗎?<br><br>No pain no gain",
        "砍掉重練<br><br>You Shall Not Pass",
        "你準備好了嗎？<br><br>Are you ready?",
        "多元與躍進<br><br>Diversity and Advancement",
        "用設計思考<br><br>Design Thinking",
        "拖<br><br>Hide",
        "先沖一杯咖啡再說<br><br>A coffee a day keeps the boss away",
        "你可能會陷入泥濘難以脫身<br><br>You are stuck",
        "放吼伊去<br><br>Let it go~ Let it go~",
        "逃避雖可恥但有用<br><br>新垣結衣 <3",
        "現在要出征<br><br>On My Way",
        "不要浪費時間<br><br>Don't waste your time",
        "過程是很重要的<br><br>The journey is the reward.",
        "尋求協助吧<br><br>Get Help",
        "不要再問了<br><br>Ask one more time and you won't see the Sun again",
        "冷靜<br><br>Keep calm and carry on",
        "你旁邊的人知道答案<br><br>Ask the one beside you.",
        "來不及了<br><br>Too Late",
        "休淡幾類<br><br>ちょっと",
        "母湯 <br><br>Mother Soup",
        "棒棒 <br><br>Bomb Bomb"
    ];